name: Dash Security Pattern Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan-patterns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Scan for dangerously_set_inner_html
        run: |
          if grep -rnw './' -e 'dangerously_set_inner_html'; then exit 1; fi

      - name: Scan for eval or exec usage
        run: |
          found=0
          for path in ./callbacks ./components ./layout ./app.py; do
            grep -rnw "$path" -e 'eval(' && found=1
            grep -rnw "$path" -e 'exec(' && found=1
          done
          if [ "$found" -eq 1 ]; then exit 1; fi